FROM centos:centos6
MAINTAINER oomatomo ooma0301@gmail.com

# env
ENV TZ JST-9

# install package
RUN rpm -Uhv http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN yum update -y
RUN yum install -y gcc gcc-c++ perl make wget tar patch

# Perl Env
ENV PERL_VERSION 5.16.3
ENV PATH /usr/local/perl-$PERL_VERSION/bin:$PATH
ENV PERL5LIB /usr/local/carton/lib/perl5/:$PERL5LIB

# install Perl
RUN curl -sL https://raw.githubusercontent.com/tokuhirom/Perl-Build/master/perl-build > /usr/bin/perl-build
RUN perl -pi -e 's%^#!/usr/bin/env perl%#!/usr/bin/perl%g' /usr/bin/perl-build
RUN chmod +x /usr/bin/perl-build
RUN perl-build $PERL_VERSION /usr/local/perl-$PERL_VERSION
RUN curl -sL http://cpanmin.us/ | /usr/local/perl-$PERL_VERSION/bin/perl - --notest App::cpanminus Carton

WORKDIR /usr/local/src/

# Carton
COPY cpanfile cpanfile
ENV PERL_CARTON_PATH /usr/local/carton
RUN carton install --path /usr/local/carton/
